#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import os, sys, argparse

# First party modules #
from autopaths                import Path
from plumbing.check_cmd_found import check_cmd

# Third party modules #
import sh

# Constants #
__version__ = '1.3.1'

# Create a shell parser #
parser = argparse.ArgumentParser(description=sys.modules[__name__].__doc__)

# Ask for the main argument #
help_msg = "The name of the module to process."
parser.add_argument("module", nargs='?', default=None, help=help_msg, type=str)

# Optional testing mode
parser.add_argument("--test", action='store_true')

# Parse the shell arguments #
args         = parser.parse_args()
path_or_name = args.module
test_mode    = args.test

# We can accept module names, filesystem paths, or default to CWD #
if path_or_name is None:
    base_dir    = Path(os.getcwd())
    module_name = base_dir.name
elif '/' in path_or_name:
    base_dir    = Path(path_or_name)
    module_name = base_dir.name
else:
    base_dir    = Path("~/repos/%s/" % path_or_name)
    module_name = path_or_name

# The python code directory #
code_dir = base_dir + module_name + '/'

# Packaging files #
toml_path  = base_dir + 'pyproject.toml'

###############################################################################
# At this point we should have the following variables:
# repo     -> /home/bob/repos/myproject/
# base_dir -> /home/bob/repos/myproject/
# code_dir -> /home/bob/repos/myproject/myproject/

# So let's confirm they exist #
base_dir.must_exist()
code_dir.must_exist()
toml_path.must_exist()

# Change directory #
os.chdir(base_dir)

# We need to make sure that all executables are available #
check_cmd('pyrattler-recipe-autogen')
check_cmd('rattler-build')

###############################################################################
# Autogenerate the recipe #
print("---------------------------")
print("-> Autogenerating rattler-build recipe")

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()
recipe_path = build_dir + 'recipe.yaml'

# Call the recipe autogen command #
recipe_autogen = sh.Command('pyrattler-recipe-autogen')
recipe_autogen('-i', str(toml_path),
               '-o', str(recipe_path),
               '--overwrite',
               _out=sys.stdout, _err=sys.stderr)

###############################################################################
# Build #
print("---------------------------")
print("-> Building package")

# Get the executable #
rattler_build = sh.Command('rattler-build')

# Launch command:
# `rattler-build build -r recipe.yaml -c conda-forge -c xapple -c bioconda`
try:
    rattler_build('build',
                   '-r', str(recipe_path),
                   '-c', 'conda-forge',
                   '-c', 'xapple',
                   '-c', 'bioconda',
                   '--output-dir', str(build_dir),
                   _out=sys.stdout,
                   _err=sys.stderr)
except sh.ErrorReturnCode as e:
    if e.stdout:
        print('-' * 60)
        msg = "Here is the stdout:"
        print(msg, e.stdout.decode('utf-8'))
    if e.stderr:
        print('-' * 60)
        msg = "Here is the stderr:"
        print(msg, e.stderr.decode('utf-8'))
    print('-' * 60)
    raise

# Get the path of the resulting package files #
artifacts = []
for root, _, files in os.walk(str(build_dir)):
    for fname in files:
        if fname.endswith(('.conda', '.tar.bz2')):
            artifacts.append(os.path.join(root, fname))
msg = "No package artifacts found in build outputs."
assert len(artifacts) > 0, msg
artifacts.sort(key=os.path.getmtime)
tar_path = artifacts[-1]

# Report the path #
print("---------------------------")
print("-> Tar path found: %s" % tar_path)

###############################################################################
# Upload #
print("---------------------------")
print("-> Uploading package")

# This uses ANACONDA_API_KEY or the keychain / auth-file.
upload_args = ['upload', 'anaconda', '--owner', 'xapple',
               '--channel', 'xapple', tar_path]
upload = rattler_build(*upload_args, _out=sys.stdout, _err=sys.stderr)

# Optional message #
if hasattr(upload, 'stderr') and upload.stderr:
    print(str(upload.stderr, "UTF-8"))

# Done #
print("Success.")
