#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using conda-build.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys

# First party modules #
from __init__                import parse_common_args
from plumbing.check_cmd_found import check_cmd

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'

args, base_dir, module_name, code_dir, toml_path, test_mode = parse_common_args(
    sys.modules[__name__].__doc__
)

# We need to make sure that all executables are available #
check_cmd('conda')