#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically submit a package to conda-forge.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys

# First party modules #
from __init__ import get_args

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
gh = sh.Command('gh')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()
recipe_path = build_dir + 'recipe.yaml'

# Print start #
print("Packaging '%s' for conda-forge submission." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################