#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically submit a package to conda-forge.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys

# First party modules #
from __init__ import get_args

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'
GITHUB_USER = 'xapple'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
gh = sh.Command('gh')
git = sh.Command('git')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()

# Print start #
print("Packaging '%s' for conda-forge submission." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################
# clone staged-recipes #
git.clone("https://github.com/conda-forge/staged-recipes", build_dir)
staged_repo = build_dir + "staged-recipes"

# cd into repo #
with sh.pushd(staged_repo):
    # create a branch #
    branch = f"add-{proj_name}"
    git.checkout("-b", branch)

    # create recipe directory #
    recipe_dir = staged_repo + "recipes" + proj_name
    recipe_dir.create_if_not_exists()

    # copy generated recipe
    pass

    # git add / commit / push
    git.add(recipe_dir)
    git.commit("-m", f"Add {proj_name}")
    git.push("-u", GITHUB_USER, branch)

    # create PR
    #gh("pr", "create", "--repo", "conda-forge/staged-recipes", "--title",   f"Add {proj_name}", "--body", f"Adding {proj_name} from PyPI.", "--head",f"{GITHUB_USER}:{branch}", )