#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using grayskull.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys, os

# First party modules #
from __init__ import get_args

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
conda       = sh.Command('conda')
conda_build = sh.Command('conda-build')
grayskull   = sh.Command('grayskull')
anaconda    = sh.Command('anaconda')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()
os.chdir(build_dir)

# Print start #
print("Packaging '%s' for anaconda distribution." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################
# Grayskull adds the line `import dist` which makes everything buggy
# Here is an example:
# Traceback (most recent call last):
#   File "/Users/sinclair/miniconda3/envs/bump/conda-bld/autopaths/test_tmp/run_test.py", line 5, in <module>
#     import dist
# ModuleNotFoundError: No module named 'dist'
# We need to remove this line...

# Create args #
args = ['pypi', proj_name]

# Check test mode #
if test_mode:
    print("-> Making a skeleton from the test PyPI index")
    args += ['--pypi-url','https://test.pypi.io/pypi/']

# Include only certain sections #
sections = '--sections package source build requirements about extra'.split()
args += sections

# Call it #
sh.grayskull(*args, _out=sys.stdout, _err=sys.stderr)

# Get the metadata file #
meta_file = build_dir + proj_name + '/meta.yaml'
assert meta_file.exists

###############################################################################
# Build #
print("---------------------------")
print("-> Building and uploading package")

# Avoid mutating global conda config. Conda config can be overridden per-process
# with env vars in the form `CONDA_<CONFIG_NAME>`, which take top precedence.
env = os.environ.copy()
env["CONDA_ANACONDA_UPLOAD"] = "true"

# Launch command #
try:
    outputs = conda_build(proj_name,
                        '-c', 'conda-forge',
                        '-c', 'xapple',
                        '-c', 'bioconda',
                        '--anaconda-upload', 'xapple',
                        _env=env,
                        _return_cmd=True,
                        _out=sys.stdout,
                        _err=sys.stderr)
except sh.ErrorReturnCode as e:
    if e.stdout:
        print('-' * 60)
        msg = "Here is the stdout:"
        print(msg, e.stdout.decode('utf-8'))
    if e.stderr:
        print('-' * 60)
        msg = "Here is the stderr:"
        print(msg, e.stderr.decode('utf-8'))
    print('-' * 60)
    raise

###############################################################################
# Clean up #
conda('build', 'purge')
build_dir.remove()

# Done #
print("Success.")