#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using pixi.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys

# First party modules #
from __init__                import parse_common_args
from plumbing.check_cmd_found import check_cmd

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'

args, base_dir, module_name, code_dir, toml_path, test_mode = parse_common_args(
    sys.modules[__name__].__doc__
)

# We need to make sure that all executables are available #
check_cmd('pixi')

###############################################################################
# Build #
print("---------------------------")
print("-> Building package")
pixi = sh.Command('pixi')

# Launch command:
try:
    pixi('build', _out=sys.stdout, _err=sys.stderr)
except sh.ErrorReturnCode as e:
    if e.stdout:
        print('-' * 60)
        msg = "Here is the stdout:"
        print(msg, e.stdout.decode('utf-8'))
    if e.stderr:
        print('-' * 60)
        msg = "Here is the stderr:"
        print(msg, e.stderr.decode('utf-8'))
    print('-' * 60)
    raise
