#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using pixi.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys
import re

# First party modules #
from __init__                import get_args
from plumbing.check_cmd_found import check_cmd

# Third party modules #
import sh

# Constants #
__version__ = '0.9.0'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
check_cmd('pixi')
pixi = sh.Command('pixi')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()

# Print start #
print("Packaging '%s' for anaconda distribution." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################
# Build #
print("---------------------------")
print("-> Building package")
pixi = sh.Command('pixi')

# You can't just run pixi because it says:
# Error:   × found pyproject.toml without tool.pixi section at directory ...
# So we need to make a special pixi.toml on the fly
pixi_toml_path = base_dir + 'pixi.toml'

# The module itself must be importable #
module = __import__(proj_name)

# Current version #
v_current = module.__version__

# Write the file #
pixi_toml_contents = f"""
[workspace]
channels = ["conda-forge"]
preview = ["pixi-build"]
platforms = ["osx-arm64"]

[package]
name = "{proj_name}"
version = "{v_current}"
license = "MIT" 

[package.build]
backend = {{ name = "pixi-build-python", version = "*" }}

[package.build.config]
noarch = true
"""

# Write the file #
pixi_toml_path.write(pixi_toml_contents.strip())

# Copy the original pyproject.toml to the build directory #
#toml_path.copy(build_dir + 'pyproject.toml')

# The requirements for the special pixi TOML file are pretty obscure
# Can't find the documentation, it keeps complaining about missing sections...
# Then it fails with:
# File "$PREFIX/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 402, in _call_hook
# pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'
pass

# Launch command:
try:
    pixi('build',
         '--path', str(pixi_toml_path),
         _out=sys.stdout, _err=sys.stderr)
except sh.ErrorReturnCode as e:
    if e.stdout:
        print('-' * 60)
        msg = "Here is the stdout:"
        print(msg, e.stdout.decode('utf-8'))
    if e.stderr:
        print('-' * 60)
        msg = "Here is the stderr:"
        print(msg, e.stderr.decode('utf-8'))
    print('-' * 60)
    raise
