#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using rattler.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys
from pathlib import Path as Pathlib

# First party modules #
from __init__ import get_args

# Third party modules #
import sh
from pyrattler_recipe_autogen.core import generate_recipe_with_config
from pyrattler_recipe_autogen.core import OutputConfig

# Constants #
__version__ = '0.9.0'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
rattler_build = sh.Command('rattler-build')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()
recipe_path = build_dir + 'recipe.yaml'

# Print start #
print("Packaging '%s' for anaconda distribution." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################
# Autogenerate the recipe #
print("---------------------------")
print("-> Autogenerating rattler-build recipe")

# Generate recipe via the Python API so we can exclude sections.
generate_recipe_with_config(
    pyproject_path=Pathlib(toml_path),
    output_path=Pathlib(recipe_path),
    config=OutputConfig(exclude_sections=["optional_dependencies", "optional_dep_groups"])
)

# But the problem is that "pyrattler-recipe-autogen" generates a recipe.yaml
# that is not accepted by "rattler-build" because of this part:
#   × expected a scalar value.
#  [build/recipe.yaml:31:11]
#  optional_dependencies:
#  ╭─▶     binary:
#  │       - binaryornot
#  │       external:
#  │       - pbs3
#  │       - sh
#  ├─▶ package:
#  ╰──── here
# So we would need to edit the recipe it generates...
pass

###############################################################################
# Build #
print("---------------------------")
print("-> Building package")

# Get the executable #
rattler_build = sh.Command('rattler-build')

# Launch command:
# `rattler-build build -r recipe.yaml -c conda-forge -c xapple -c bioconda`
try:
    rattler_build('build',
                   '-r', str(recipe_path),
                   '-c', 'conda-forge',
                   '-c', 'xapple',
                   '-c', 'bioconda',
                   '--experimental',
                   '--output-dir', str(build_dir),
                   _out=sys.stdout,
                   _err=sys.stderr)
except sh.ErrorReturnCode as e:
    if e.stdout:
        print('-' * 60)
        msg = "Here is the stdout:"
        print(msg, e.stdout.decode('utf-8'))
    if e.stderr:
        print('-' * 60)
        msg = "Here is the stderr:"
        print(msg, e.stderr.decode('utf-8'))
    print('-' * 60)
    raise