#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""
A script to automatically update python modules on anaconda using conda-build.
See the README.md file for more information.

Written by Lucas Sinclair.
MIT Licensed.
Contact at www.sinclair.bio
"""

# Built-in modules #
import sys, os

# Internal modules #
from __init__ import get_args

# Third party modules #
import sh

# Constants #
__version__ = '0.9.1'

# Get command line arguments #
doc = sys.modules[__name__].__doc__
base_dir, proj_name, code_dir, toml_path, test_mode = get_args(doc)

# We need to make sure that all executables are available #
conda = sh.Command('conda')

# Create a temporary directory #
build_dir = base_dir + 'build/'
build_dir.create_if_not_exists()
os.chdir(build_dir)

# Print start #
print("Packaging '%s' for anaconda distribution." % proj_name)
print("---------------------------")
print("Using temporary directory '%s'." % build_dir)

###############################################################################
# Autogenerate the recipe #
print("---------------------------")
print("-> Autogenerating skeleton")

# Launch command:
conda('skeleton', 'pypi', proj_name,
      _out=sys.stdout,
      _err=sys.stderr)

# This strategy doesn't work because it depends on `setup.py` exisiting.from
# FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/44/gb9f28yd4tx5wfh8t4116ftm0000gn/T/tmpufhcvf8uconda_skeleton_myproj-1.6.2.tar.gz/myproj-1.6.2/setup.py'
# So we would need to create temporary setup.py on the fly...
pass